sudo: false  # Use travis' container based infra
language: python
dist: focal
# Versions are deliberately out of order to get a diverse sample first
python:
  - 3.8
  - 3.5
  - 3.6
  - 3.7
  - pypy3
cache: pip
install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt
script: python setup.py test
