name: Tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # 13:22 UTC on Tuesdays
    - cron: "22 13 * * TUE"
  workflow_dispatch:
  repository_dispatch:
    types: [tests]

# Based on https://github.com/ymyzk/tox-gh-actions#tox-gh-actions-configuration
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
